// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using XamarinSignalR;

namespace XamarinSignalR.iOS
{
	public partial class TextEntryCell : UITableViewCell
	{
		public static readonly NSString Key = new NSString("TextEntryCell");
		public static readonly UINib Nib;

		static TextEntryCell()
		{
			Nib = UINib.FromName("TextEntryCell", NSBundle.MainBundle);
		}

		public TextEntryCell(IntPtr handle) : base (handle){}

		public static TextEntryCell Create()
		{
			return (TextEntryCell)Nib.Instantiate(null, null)[0];
		}

		public void Update(Response response)
		{
			ValueLabel.Text = response.Message;
			SizeLabel.Text = response.Size;
			DelayLabel.Text = response.Delay;
		}

	}
}
